apiVersion: v1
kind: Service
metadata:
  name: prom
spec:
  type: ClusterIP
  selector:
    app: prom
  ports:
    - protocol: TCP
      name: prom
      port: 9090
    - protocol: TCP
      name: statsd
      port: 9125
    - protocol: TCP
      name: statsd_prom
      port: 9102
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graph-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: "prom.in.cluster.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prom
                port:
                  number: 9090
